### ISSUE TITLE
Prevent React state update on an unmounted component

### ISSUE THREAD

**Issue by huextrat** [audienzzag/react-native-audienzz#2]
The following code will produce this warning if the component is unmounted : `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

https://github.com/audienzzag/react-native-audienzz/blob/0213ce8760754d2d2d161d8c9f9bb091e8a55044/src/AppNexusBanner/AppNexusBanner.tsx#L127-L132

To prevent this warning please check if the component is still mounted before doing something in the `setTimeout`. Something like the following should work:

```
useEffect(() => {
    let isCancelled = false;
    setTimeout(() => {
      if (!isCancelled) {
        LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
        setBannerStyles({ width, height });
      }
    }, 300);
    return () => {
      isCancelled = true;
    };
  }, [width, height]);
```

**Comment by alex-ragin** [comment]
Thanks @huextrat for pointing this out. We've fixed this possible memory leak.
